name: Create Release

on:
  push:
    tags:
      - "v*.*.*" # Matches v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }} 